version: '3'
services:
  # Go application service
  app:
    build:
      context: . # Use the current directory for building
    ports:
      - "3333:3333" # Map host port 8080 to container port 8080
    depends_on:
      - postgres # Make sure PostgreSQL is ready before starting the app

  # PostgreSQL service
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432
    command: postgres -c max_connections=1000 # Increase max_connections for development

  # A service for initializing the database (e.g., using a script)
  initdb:
    build:
      context: ./initdb # Create a separate directory for the initialization script
    depends_on:
      - postgres

# Define networks if needed
networks:
  # Optional: Create a custom network
  mynetwork:
